# Generated by Django 3.2.8 on 2021-12-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.CharField(choices=[('Allergies', '101'), ('Birth Control', '102'), ('Common Cold', '103'), ('Chronic Pain', '104'), ('Digestive Health', '105'), ('Eczema', '106'), ('Heart Disease', '107'), ('Oral Health', '108')], default='Allergies', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
