# Generated by Django 3.2.8 on 2021-12-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20211203_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('101', 'Allergies'), ('102', 'Birth Control'), ('103', 'Common Cold'), ('104', 'Chronic Pain'), ('105', 'Digestive Health'), ('106', 'Eczema'), ('107', 'Heart Disease'), ('108', 'Oral Health'), ('109', 'Head'), ('110', 'forehead')], default='101', max_length=20),
        ),
    ]
