# Generated by Django 3.2.8 on 2022-01-09 06:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='affiliate_link',
            field=models.URLField(default=datetime.datetime(2022, 1, 9, 6, 21, 46, 502469, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('101', 'Addiction'), ('102', 'Beauty'), ('103', 'Dental Health'), ('104', 'Dietary Supplements'), ('105', 'Diets & Weight Loss'), ('106', 'Exercise & Fitness'), ('107', 'General'), ('108', 'Meditation'), ('109', 'Men’s Health'), ('110', 'Mental Health'), ('111', 'Nutrition'), ('112', 'Remedies'), ('113', 'Sleep and Dreams'), ('114', 'Spiritual Health'), ('115', 'Strength Training'), ('116', 'Women’s Health'), ('117', 'Yoga')], default='101', max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
